package app.subconsciously.helper

object PromptRepository {

    private val reflectionPrompts = arrayOf(
        "Boredom grows ideas. Scrolling doesn't. Proven.",
        "6 seconds kills a craving. Science said so.",
        "Your brain needs boredom to reset. True story.",
        "Dopamine spikes from scrolling fade in minutes. Science said so.",
        "Walking 10 minutes sharpens focus. Proven.",
        "The default mode network fires when you rest. True story.",
        "Multitasking cuts your IQ by 10 points. Science said so.",
        "Sleep clears brain toxins every night. Proven.",
        "A 5-minute break doubles output. True story.",
        "Cravings peak at 3 minutes then fade. Science said so.",
        "Your attention span outlasts the urge. Proven.",
        "Rest is productive. The brain proved it.",
        "Sunlight in the morning resets your whole clock. True story.",
        "Deep breathing lowers cortisol in 90 seconds. Science said so.",
        "Habits form faster when rewarded immediately. Proven.",
        "Your prefrontal cortex is stronger than the urge. True story.",
        "Boredom activates the creative default mode network. Science said so.",
        "20 minutes of focus beats 2 hours distracted. Proven.",
        "The craving will pass. Biology guarantees it.",
        "Your brain prunes unused habits. True story.",
        "One deep breath reduces anxiety measurably. Science said so.",
        "Memory consolidates during rest, not screens. Proven.",
        "Novelty seeking is a loop. You can exit.",
        "Dopamine is meant for real wins. True story.",
        "Focus returns faster than you think. Science said so.",
        "Silence grows your best thinking. Proven.",
        "The urge is just a brain signal. It fades.",
        "Sleep deprivation mimics being drunk. True story.",
        "Scrolling shrinks your patience. Science said so.",
        "Your brain clears toxins during deep sleep. Proven.",
        "Boredom precedes breakthrough. Every time. Proven.",
        "Dopamine resets during quiet moments. True story.",
        "10 minutes outside changes brain chemistry. Science said so.",
        "Cravings are 3 minutes max. You have 3 minutes.",
        "The pause is the power. Science said so.",
        "Focused work grows gray matter. True story.",
        "Rest activates the network that solves problems. Proven.",
        "Your brain hates multitasking. It told the scientists.",
        "A nap beats a coffee. Science said so.",
        "Checking phones 96 times a day is average. You can do better.",
        "Attention is trainable. Proven.",
        "The idle mind is the creative mind. True story.",
        "Stress hormones drop after 20 minutes outdoors. Science said so.",
        "Your future memory depends on sleep tonight. Proven.",
        "Daydreaming builds empathy. True story.",
        "One task at a time doubles accuracy. Science said so.",
        "Willpower is a muscle. It recovers with rest.",
        "The brain rewards completion, not scrolling. Proven.",
        "Quiet time is when neurons reorganize. True story.",
        "Craving intensity drops without reinforcement. Science said so.",
        "Your concentration span is longer than your feed. Proven.",
        "The brain loves finishing things. Give it one.",
        "Exercise grows new brain cells. True story.",
        "Notification sounds spike cortisol. Science said so.",
        "Reading improves focus better than apps. Proven.",
        "Your brain builds focus like a muscle. True story.",
        "Distraction breaks cost 23 minutes to recover. Science said so.",
        "Idle hands spark the default mode network. Proven.",
        "The best ideas come between tasks. True story.",
        "Dopamine from real achievements lasts longer. Science said so.",
        "Your heart rate drops in nature. Proven.",
        "Screens before bed delay sleep by 1 hour. True story.",
        "Boredom is the brain asking for depth. Science said so.",
        "Writing thoughts clears mental load. Proven.",
        "Your willpower peaks in the morning. True story.",
        "Multitasking causes more errors than alcohol. Science said so.",
        "A full night's sleep rewires learning. Proven.",
        "Silence is stimulating to the resting brain. True story.",
        "Breathing through your nose calms the nervous system. Science said so.",
        "The pull to check is a trained reflex. You can untrain it.",
        "Cold water on your face resets alertness. Proven.",
        "Your brain thrives on routine and rest. True story.",
        "Attention restores in green spaces. Science said so.",
        "The craving cycle weakens every time you pause. Proven.",
        "Flow state requires 20 uninterrupted minutes. True story.",
        "Your dopamine system is designed for meaning. Science said so.",
        "Short focused bursts outperform long distracted sessions. Proven.",
        "The default mode network is where insight lives. True story.",
        "Napping 20 minutes sharpens memory. Science said so.",
        "Stress shrinks the hippocampus. Rest grows it back. Proven.",
        "Your brain is still working when you pause. True story.",
        "Habitual scrolling reshapes neural pathways. Science said so.",
        "One focused hour beats three scattered ones. Proven.",
        "The brain craves completion more than continuation. True story.",
        "Morning light sets your circadian rhythm. Science said so.",
        "Resisting once makes the next resist easier. Proven.",
        "Your attention is the most valuable thing you own. True story.",
        "Idle mind equals default mode equals problem solving. Science said so.",
        "Walking outside lowers rumination. Proven.",
        "The urge shrinks when observed. True story.",
        "Breathing slowly activates the vagus nerve. Science said so.",
        "Your brain stores memories in sleep. Proven.",
        "Distraction craving peaks then drops in 90 seconds. True story.",
        "Focused effort rewires your brain faster. Science said so.",
        "Breaks make you smarter. Proven.",
        "Your brain grows during offline time. True story.",
        "Multitasking burns more glucose. Science said so.",
        "The best problem solver is a rested brain. Proven.",
        "Sunlight boosts serotonin naturally. True story.",
        "Every pause trains your brain toward patience. Science said so.",
        "Curiosity is a better motivator than dopamine hits. Proven.",
        "Your focus window grows with daily practice. True story.",
        "Anxiety drops after 10 minutes of movement. Science said so.",
        "Boredom is creative fuel. Scrolling burns it. Proven.",
        "Deep sleep doubles memory retention. True story.",
        "Phone notifications fragment focus into tiny useless pieces. Science said so.",
        "Your brain can focus for 90-minute cycles. Proven.",
        "Micro-breaks prevent decision fatigue. True story.",
        "Cold showers increase dopamine by 250%. Science said so.",
        "Your imagination activates during silence. Proven.",
        "Stress lowers immune function within hours. True story.",
        "Scrolling before sleep reduces dream quality. Science said so.",
        "The brain rewards habits not impulses. Proven.",
        "You think better after a walk. True story.",
        "Craving signals last under 5 minutes. Science said so.",
        "Focused attention shrinks with each distraction. Proven.",
        "Your neurons prune during sleep. True story.",
        "Limiting choices reduces decision fatigue. Science said so.",
        "Stillness is not laziness. It's brain fuel. Proven.",
        "The prefrontal cortex calms cravings. Science said so.",
        "Your brain defaults to creativity when idle. True story.",
        "Social media triggers the same circuits as gambling. Science said so.",
        "Mindful breathing lowers blood pressure. Proven.",
        "Your memory improves after rest. True story.",
        "Habitual checking weakens impulse control. Science said so.",
        "Focused reading builds working memory. Proven.",
        "Daydreaming is not wasted time. True story.",
        "The urge to scroll is chemical. It passes. Science said so.",
        "Rest is where the brain processes today. Proven.",
        "Your brain prefers depth over speed. True story.",
        "Sunlight before noon improves sleep at night. Science said so.",
        "The pause between thoughts is where clarity lives. Proven.",
        "Dopamine from real progress is more lasting. True story.",
        "Your nervous system needs 20 quiet minutes daily. Science said so.",
        "Attention is finite. You get to choose where it goes.",
        "Exercise increases BDNF, your brain's growth protein. True story.",
        "Screens in the dark harm melatonin production. Science said so.",
        "Your brain loves single-tasking. Proven.",
        "The resting state is a working state. True story.",
        "One minute of silence rewires the stress response. Science said so.",
        "Craving loops shorten with every successful pause. Proven.",
        "Your best thinking happens away from screens. True story.",
        "Sleep is when your brain files the day. Science said so.",
        "Focused attention is a competitive advantage. Proven.",
        "The app is designed to keep you. You're stronger. True story.",
        "Breathing activates the parasympathetic system. Science said so.",
        "Imagination and memory use the same brain network. Proven.",
        "Curiosity lights up the reward circuit naturally. Science said so.",
        "The mind wanders to solve, not to waste. Proven.",
        "Dopamine dips after every scroll. Science said so.",
        "Your brain resets in under 10 minutes offline. Proven.",
        "Physical activity is the fastest mood fix. True story.",
        "Habitual distraction retrains the brain away from depth. Science said so.",
        "Resting grows your capacity for focus. Proven.",
        "Silence is where the default mode network thrives. True story.",
        "Your cortisol drops when you step outside. Science said so.",
        "Boredom without escape breeds breakthrough ideas. Proven.",
        "The brain consolidates skills during downtime. True story.",
        "Notifications spike adrenaline. Science said so.",
        "Your attention is more powerful than the algorithm. Proven.",
        "One focused session builds more than hours of browsing. True story.",
        "Craving intensity peaks fast and drops fast. Science said so.",
        "Walking clears mental fog. Proven.",
        "The brain thrives with 8 hours of sleep. True story.",
        "Screen time before bed costs 2 hours of deep sleep. Science said so.",
        "Every distraction adds to your cognitive load. Proven.",
        "Your brain stores facts better after rest. True story.",
        "The urge to check is dopamine talking. It fades. Science said so.",
        "Focused effort today rewires tomorrow's defaults. Proven.",
        "Thinking creatively needs a bored brain. True story.",
        "Blue light tricks the brain into daytime mode. Science said so.",
        "Your working memory holds 4 things max. Proven.",
        "Movement and focus are deeply linked. True story.",
        "The craving has a ceiling. You're past it now. Science said so.",
        "Quiet time is when the hippocampus consolidates learning. Proven.",
        "Your attention is finite and precious. True story.",
        "Distraction is a habit, and habits can be changed. Science said so.",
        "Momentum builds in single-task focus. Proven.",
        "The idle brain generates the most original thought. True story.",
        "Hydration improves focus by 14%. Science said so.",
        "Your brain recharges the same way your phone does. Proven.",
        "A real laugh reduces cortisol measurably. True story.",
        "Habitual calm rewires the stress response. Science said so.",
        "Focus creates flow. Flow creates fulfillment. Proven.",
        "Your best creative work starts in silence. True story.",
        "Every scroll trains your brain to need more. Science said so.",
        "Rest is not the opposite of productivity. It's the source. Proven.",
        "Your imagination fires the moment screens turn off. True story.",
        "Stress hormones interfere with memory formation. Science said so.",
        "Your brain is always remodeling itself. Proven.",
        "Distraction loops activate the same reward pathway as sugar. True story.",
        "The ability to wait is the ability to win. Science said so.",
        "Staring into distance relaxes the eye and the mind. Proven.",
        "Your brain is more creative after sleep. True story.",
        "Slow breath equals slow heart rate equals calm mind. Science said so.",
        "The default mode network solves problems you forgot you had. Proven.",
        "Rest between tasks improves next-task performance. True story.",
        "Your decision quality drops after 3 hours of screen time. Science said so.",
        "Boredom trains the brain to self-generate reward. Proven.",
        "The pause is powerful. Science keeps proving it.",
        "Your brain grows new connections during rest. True story.",
        "Craving disappears faster when you don't feed it. Science said so.",
        "A short walk changes neurochemistry. Proven.",
        "Sleep is the brain's maintenance mode. True story.",
        "Habitual quiet grows your focus capacity. Science said so.",
        "The best version of you needs 8 hours. Proven.",
        "Your brain prefers repetition over randomness for learning. True story.",
        "Cortisol from screens delays sleep onset. Science said so.",
        "Idle time is not wasted time. It's brain time. Proven.",
        "The wandering mind is the exploring mind. True story.",
        "Resistance builds the neural circuits for control. Science said so.",
        "Your focus doubles after a screen-free hour. Proven.",
        "Deep sleep is when memories become permanent. True story.",
        "Attention training changes brain structure. Science said so.",
        "The reward of finishing beats the reward of scrolling. Proven.",
        "Your creativity spikes when you stop trying. True story.",
        "Distraction costs more time than it saves. Science said so.",
        "Rest well. Work better. Proven.",
        "Your nervous system heals during stillness. True story.",
        "The brain prefers one thing done over ten started. Science said so.",
        "Silence improves your ability to hear yourself think. Proven.",
        "Boredom triggers the release of new neural connections. True story.",
        "Your mood resets after 20 minutes in daylight. Science said so.",
        "Focus is a skill. You're practicing it right now. Proven.",
        "Craving cycles weaken without reinforcement. True story.",
        "The brain uses 20% of your body's energy. Feed it rest. Science said so.",
        "Unplugging grows perspective. Proven.",
        "Your subconscious works hardest when you're relaxed. True story.",
        "Each pause trains your dopamine system toward depth. Science said so.",
        "Flow state only enters when distractions exit. Proven.",
        "Your hippocampus files memories during offline time. True story.",
        "Exercise builds the brain as much as the body. Science said so.",
        "Stillness is the fastest path to clarity. Proven.",
        "The more you rest, the sharper you return. True story.",
        "Your brain thrives on cycles of effort and rest. Science said so.",
        "Real boredom is a signal of creative readiness. Proven.",
        "Screens fragment attention. Silence restores it. True story.",
        "10 deep breaths changes your brain state. Science said so.",
        "The pausing brain is the planning brain. Proven.",
        "Your focus is always recovering. Give it a chance. True story.",
        "Chronic distraction rewires the prefrontal cortex. Science said so.",
        "Step outside. The research agrees. Proven.",
        "Your brain's reward system prefers meaning over novelty. True story.",
        "Sleep debt accumulates. So does rest debt. Science said so.",
        "Silence is a stimulant for the creative mind. Proven.",
        "Your brain doesn't multitask. It switches. Badly. True story.",
        "The desire to scroll is trained. So is the desire to stop. Science said so.",
        "Resting eyes rests the whole brain. Proven.",
        "Momentum starts with one full minute of focus. True story.",
        "The craving curve peaks then crashes. Science said so.",
        "Your default mode network is never truly off. Proven.",
        "Boredom is the brain warming up. True story.",
        "Doing nothing is doing something for your brain. Science said so.",
        "Rest converts short-term memory to long-term. Proven.",
        "Your brain builds focus in offline blocks. True story.",
        "Blue light suppresses melatonin by 3 hours. Science said so.",
        "Daydreaming activates empathy circuits. Proven.",
        "The itch to check fades if you wait 90 seconds. True story.",
        "Your attention is more valuable than any feed. Science said so.",
        "Focused work is the fastest path to confidence. Proven.",
        "The brain loves novelty, but needs depth to grow. True story.",
        "Micro-pauses reduce mental fatigue by 30%. Science said so.",
        "Your thoughts get clearer after movement. Proven.",
        "Sleep is the best learning enhancer known. True story.",
        "Resisting the urge retrains the reward circuit. Science said so.",
        "Your brain repairs itself while you rest. Proven.",
        "Mindfulness measurably grows the prefrontal cortex. True story.",
        "Attention is the currency of the modern world. Science said so.",
        "Stillness resets your baseline stress level. Proven.",
        "The first step out the door changes brain chemistry. True story.",
        "Cravings have a timer. It always runs out. Science said so.",
        "Your brain is more active at rest than you think. Proven.",
        "Reading fiction grows empathy. True story.",
        "Dopamine loves anticipation more than delivery. Science said so.",
        "Your breathing controls your mental state. Proven.",
        "The brain that rests focuses best. True story.",
        "Digital silence is the new deep work. Science said so.",
        "Your concentration improves every time you resist. Proven.",
        "Boredom has a graduation: ideas. True story.",
        "20 minutes of nature lowers cortisol. Science said so.",
        "Your brain builds patience one pause at a time. Proven.",
        "The urge is a wave. It passes. True story.",
        "Habitual screen time rewires reward pathways. Science said so.",
        "The idle mind is building your next breakthrough. Proven.",
        "Your body's rest is your brain's work. True story.",
        "Focused work changes your brain in 8 weeks. Science said so.",
        "The pausing brain becomes the performing brain. Proven.",
        "Your biological reward system runs on real wins. True story.",
        "Flow requires boredom to begin. Science said so.",
        "A rested brain sees solutions a tired one misses. Proven.",
        "Your impulse control is stronger than the algorithm. True story.",
        "The brain prunes what isn't used. Prune wisely. Science said so.",
        "One full minute of stillness shifts your state. Proven.",
        "Your best ideas haven't arrived yet. Give them room. True story.",
        "The default mode network is your real creative tool. Science said so.",
        "Offline time is high-performance recovery. Proven.",
        "Your focus is a muscle. Every pause is a rep. True story.",
        "Real rest creates real momentum. Science said so.",
        "You came back. That's the whole skill. Proven."
    )

    private val unblockPrompts = arrayOf(
        "Your future self remembers why this matters. Your present self just forgot for a second.",
        "You built this wall for a reason. It's still a good reason.",
        "The version of you who gets there didn't unlock this. The version who wins won't either.",
        "Future you is grateful you didn't open it. That gratitude is real.",
        "This block is a promise you made to yourself. It still counts.",
        "Your goals are still standing. This app isn't one of them.",
        "The reason you set this up was real. It still is.",
        "You decided this in a clear moment. Trust that version of you.",
        "Future you has the life you're building right now. Don't interrupt that.",
        "The wall is doing its job. So are you.",
        "You'll thank yourself later. That later is becoming now.",
        "This is the version of you that keeps promises. Good.",
        "The distraction will still be there after you've done what matters.",
        "Your future self is watching. They're proud of this moment.",
        "You blocked this because you have somewhere better to be.",
        "The best version of you set this up. Honor that version.",
        "Every time you walk away here, future you gains ground.",
        "Your goals don't pause when you scroll. You do.",
        "This decision was made with purpose. That purpose hasn't expired.",
        "Future you is being shaped right now. Shape wisely.",
        "The clarity that set this block is clearer than the craving.",
        "You have a direction. This app isn't in it.",
        "The promise you made yourself is still valid.",
        "Your future self is the one who built the habits. This is one of them.",
        "Nothing here is worth what you're building out there.",
        "The life you want lives on the other side of this moment.",
        "Your past self already made the smart choice. Respect that.",
        "Future you doesn't regret skipping this. Present you won't either.",
        "You set this up on purpose. The purpose remains.",
        "The craving is temporary. What you're building is permanent.",
        "This block is proof you take yourself seriously. Keep going.",
        "Your goals didn't change. Your attention just wandered.",
        "The person you're becoming doesn't need this app right now.",
        "You gave yourself this protection because you deserve it.",
        "There is a version of you that already won. They didn't check this.",
        "Your time is the most valuable thing you have. This isn't a good use.",
        "The boundary you set is still serving you. Let it.",
        "Future you has better habits because present you built them here.",
        "You decided in your best moment. This is not your worst.",
        "Your purpose is still standing. This scroll isn't.",
        "The version of you who set this block knew something. Listen.",
        "Your attention is being saved for something that matters.",
        "This wall is loyalty to yourself.",
        "The future you want is built in moments like this one.",
        "You didn't come this far to open an app that takes you nowhere.",
        "The life you're building doesn't include this detour.",
        "Your intentions were clear. They still are.",
        "Future you has more focus because you practiced here.",
        "The block is working. You're working. That's the whole plan.",
        "Your best self put this here. Your best self is still right.",
        "You made a commitment. This is what keeping it looks like.",
        "The goal you set this for hasn't moved. Only your attention did.",
        "Your future self isn't on this app. Go find them.",
        "This moment is a small test. You already know how to pass it.",
        "The wall stands because you built it with purpose.",
        "Every time you respect this block, you earn back your focus.",
        "The reason you blocked this was real then. It's real now.",
        "Your attention belongs to your future. Not this feed.",
        "You had clarity when you set this up. That clarity is still true.",
        "Future you is counting on present you to hold the line.",
        "Nothing in here is worth breaking your momentum for.",
        "The block is a gift you gave yourself. Receive it.",
        "Your goals are still waiting. They're patient. Be worthy of that.",
        "You don't need this to feel okay. You already proved that.",
        "The future you're building is already proud of this pause.",
        "This block is a boundary. Boundaries are self-respect in action.",
        "Decisions made in clarity are smarter than decisions made in craving.",
        "The life you described wanting didn't include this scroll.",
        "Your focus is a resource. You chose to protect it.",
        "Future you is living what present you is building. Build well.",
        "The path forward isn't through this app.",
        "You blocked this because you know your patterns. You still know them.",
        "Your future is one consistent decision away. This is that decision.",
        "This wall is a version of you that never stopped caring.",
        "The craving is a visitor. It doesn't have to stay.",
        "Your best work happens when this stays closed. You knew that.",
        "Future you doesn't look back on the scrolling. They look back on the work.",
        "You have a plan. This app wasn't in it.",
        "The block was intentional. So is walking away from it now.",
        "Your momentum is more valuable than whatever's in this feed.",
        "The decision to block was made for a reason. You know the reason.",
        "Future you inherited the habits you build today.",
        "You don't have to go in. You already know that.",
        "The strongest version of you set this block. Trust it.",
        "Your goals didn't change. Your impulse did. Impulses pass.",
        "This is the smallest resistance you'll face today. You've got it.",
        "Future you has one more reason to be grateful you held this line.",
        "The app will be there. Your momentum won't rebuild itself.",
        "You chose your future over this feed once already. Do it again.",
        "This wall is part of the strategy. The strategy is working.",
        "Your clarity set this block. Your clarity is still correct.",
        "The version of you that makes it put systems in place. This is one.",
        "Your focus is the most precious resource you own. Protect it.",
        "Future you is proud of this choice before you've even made it.",
        "You built this friction on purpose. Let it work.",
        "The craving for this app isn't the same as a need for this app.",
        "Future you will remember this as the time you chose direction over distraction.",
        "Nothing changes if nothing changes. You built this to change things.",
        "The block is doing exactly what you designed it to do.",
        "Your purpose is louder than your impulse. Listen to the louder one.",
        "You set this limit in your clearest moment. This is not the moment to override it.",
        "The future you want doesn't start with opening this app.",
        "Your habit of walking away here is building the focus you need.",
        "Future you doesn't have regrets about skipping this. Present you won't either.",
        "This is the version of you who keeps promises to yourself.",
        "The wall is not punishment. It's protection.",
        "Your direction is set. This is not it.",
        "Future self has bigger concerns than this feed. Train that version now.",
        "The goal matters more than the scroll. You knew that when you made this block.",
        "Your best moments came when this was closed. That's still true.",
        "You wrote yourself a message when you set this up. The message says no.",
        "The person you want to become is watching the choice you make here.",
        "Your habits compound. This pause compounds into focus.",
        "Future you is grateful for every time present you held the line.",
        "The boundary is part of your identity now. Respect yourself.",
        "Your direction didn't change. Your attention just needed a reminder.",
        "This block is the infrastructure of your future. It's solid.",
        "You don't scroll your way to where you're going.",
        "The reason you built this still stands. The reason always stands.",
        "Your future self is living proof that this decision matters.",
        "You don't need to undo what your best self built.",
        "This wall was built with your future in mind. Your future is still in the plan.",
        "Future you has better things to do. Right now you have better things to do.",
        "The habit of walking away from this is shaping the person you're becoming.",
        "You decided this deserved a block. That judgment was correct.",
        "Your focus is finite. This app doesn't deserve today's share.",
        "Future you is not nostalgic for the scroll. They're grateful you stopped.",
        "The discipline to set this block is the same discipline that gets you there.",
        "Your intentions are valid. Your block is valid. Walk away.",
        "Nothing on the other side of this screen is worth your trajectory.",
        "You're not missing out. You're opting in to something better.",
        "Future you is proof the system works. Stay in it.",
        "The block is a note to yourself: you've been here before, it's not worth it.",
        "Your momentum is a real thing. Protect it like one.",
        "This is the moment where your future gets decided. You know what to choose.",
        "The app will still exist later. Your window of focus won't.",
        "You built this block in a moment of clarity. Clarity was right.",
        "Your goals are patient. They're waiting. Don't make them wait longer.",
        "Future you inherited the work you do today. Leave them something good.",
        "The decision has already been made. You made it when you set this up.",
        "Your future self has a clearer head because you protected your attention here.",
        "This moment is a small test you already know how to pass.",
        "The block is your past self looking out for your future self.",
        "Your habits live in small decisions like this one. Make a good one.",
        "Future you knows that every wall held was worth it.",
        "This is what self-respect looks like in practice. Practice it.",
        "You set this limit because the alternative costs too much. It still does.",
        "Your path forward is clear. This app is not on it.",
        "The version of you who made it to the goal started here. Walk away.",
        "Future you doesn't need this app. Present you doesn't either.",
        "You made this harder to open because easier-to-open cost you too much.",
        "The reason you set this block is still the right reason.",
        "Your focus is rebuilding every time you honor this.",
        "Future you has a life you're proud of. Build it now.",
        "This block is a tool. Tools work when you let them.",
        "The person you were when you set this block trusted you. Don't break that.",
        "Future you doesn't regret the scrolls they skipped. They regret the ones they didn't.",
        "Nothing in this app changes the goal you have outside of it.",
        "You're protecting your momentum. That's one of the most valuable things you can do.",
        "Future you is investing in what you do right now.",
        "The wall is working. You are working. Stay working.",
        "Your intentions outlast your impulses. Always.",
        "This is not the version of you that breaks its own systems.",
        "Future you has a stronger attention span because you built it here.",
        "The block was thoughtful. Your reaction to it doesn't have to be.",
        "Your goals are still live. This app is a pause on them.",
        "Future you doesn't look back and wish they scrolled more.",
        "This decision is small. The habit it builds is not.",
        "You came here with a purpose. The app isn't it.",
        "The clarity you had when you set this block is stronger than the craving you feel now.",
        "Your future is not in this feed. It never was.",
        "This block is a small act of loyalty to yourself.",
        "Future you built their habits in moments exactly like this one.",
        "The wall is not stopping you. It's steering you.",
        "Your best self made this. Your best self is still right.",
        "You're not quitting. You're choosing.",
        "Future you has what you're building. Don't stop building.",
        "The block is proof you have a vision. The vision is still valid.",
        "Your habits right now are writing your future. Write something good.",
        "Future you remembers the day you held the line. Today might be it.",
        "This block was a promise. Promises kept build trust with yourself.",
        "Your attention is worth more than this feed has ever given back.",
        "Future you is shaped by present you. Shape carefully.",
        "The block isn't the enemy of your joy. This feed is.",
        "You walked past this before. You can walk past it again.",
        "Your goal is still there. It's been waiting patiently.",
        "Future you has the focus you're building right now.",
        "This app is not where your story goes. You wrote that already.",
        "The wall holds every time you let it. Let it.",
        "Your future isn't in scroll mode. It's in build mode.",
        "You set this because you knew what this costs. It still costs the same.",
        "Future you is living on the attention you protect today.",
        "The block is a compass. It still points the right way.",
        "Your purpose is a louder voice than the algorithm. Listen to it.",
        "This decision belongs to your best self. Let them decide.",
        "Future you will remember this as part of how it all came together.",
        "The wall is on your side. Always has been.",
        "You blocked this because you're building something. Keep building.",
        "Future you doesn't waste time on what present you chose to block.",
        "Your intentions are facts. Act on the facts.",
        "This block is you, from your best day, speaking to you now.",
        "Future you has the calm you're practicing here.",
        "The block is a boundary. Boundaries are how you keep yourself.",
        "Your goals don't disappear when you open this. They just fall behind.",
        "Future you is grateful for the pause more than the feed.",
        "You're not missing out. You're opting out of what costs you.",
        "This is the smallest decision with the biggest pattern attached.",
        "Future you has the life you're protecting space for right now.",
        "The reason this is blocked is valid. The reason is still valid.",
        "Your discipline in moments like this compounds into something real.",
        "This wall exists because you respect your own time.",
        "Future you is built from all the times you chose direction.",
        "The block reminds you: you decided this was a cost. It still is.",
        "Your focus is being trained. This is one of the reps.",
        "Future you has more time because you didn't lose it here.",
        "The decision to walk away is easier than it seems right now.",
        "Your past self made a smart call. Don't undo it.",
        "Future you has the wins that came from protecting the work.",
        "This block stands between you and a habit you're trying to break.",
        "Your goal is the constant. This app is the variable.",
        "Future you is proud of how consistent you became.",
        "The wall is a habit in itself. A good one.",
        "Your life outside this app is where the story happens.",
        "This is not where you're going. You set that destination already.",
        "Future you didn't get there by breaking their own rules.",
        "The block is not the problem. It's the solution you built.",
        "Your vision set this up. Your vision is still correct.",
        "Future you has clarity because present you practiced it here.",
        "The wall is working for you whether you feel it or not.",
        "Your future self lives on the other side of this choice.",
        "This block is the infrastructure of the life you want. Don't dismantle it.",
        "Future you trusts present you to hold this. You can.",
        "Your attention is finite. Your dreams are not. Prioritize accordingly.",
        "The reason you built this block is a good reason. It's still a good reason.",
        "Future you already broke this loop, starting here.",
        "This wall is a commitment kept. Keep it.",
        "Your momentum doesn't rebuild as fast as it breaks. Protect it.",
        "Future you has the focus that came from practicing this exact moment.",
        "The block is a small act of care for the person you're becoming.",
        "Your purpose is more durable than this craving. Wait it out.",
        "This is not the app that gets you where you're going.",
        "Future you remembers the choices that stacked. This is one of them.",
        "The wall is aligned with your goals. So is walking away.",
        "Your attention is the bridge to your future. Don't burn it here.",
        "Future you has better defaults because present you trained them.",
        "This block is trust you placed in yourself. Honor it.",
        "Your best life doesn't run through this app. You already knew.",
        "Future you is watching. Future you is grateful. Walk away.",
        "The block is a vote for the person you want to be.",
        "Your goals are intact. Your focus is recoverable. Walk away.",
        "This block is the version of you that doesn't make the same mistake twice.",
        "Future you has consistency because past you built the system.",
        "Your work is waiting. It's more patient than this app, and more rewarding.",
        "The wall is still the right call. It will always be.",
        "Future you built something. It started with moments like this.",
        "Your attention is being saved for something worth saving it for.",
        "This block is a note from your most intentional self. Read it.",
        "Future you has fewer regrets because present you made better choices.",
        "The wall is trust in yourself, made solid.",
        "Your path didn't go through this app. It never did.",
        "Future you has the energy you didn't waste scrolling.",
        "This block is one part of the whole system. Don't break the system.",
        "Your direction is still clear. Don't let a craving cloud it.",
        "Future you has the wins because present you made the trade.",
        "The block stands because you set it up when you were thinking clearly.",
        "Your future self is living in the compound interest of good choices.",
        "Future you has the habits that started here. Start them here.",
        "The block is working. You walking away proves it.",
        "Your momentum is worth more than a few seconds of scroll.",
        "Future you has the focus you practiced when it was hard.",
        "This block was built to serve you. Let it serve.",
        "Your best self didn't place this block to be ignored. Listen.",
        "Future you has the results of the systems you kept.",
        "The wall is part of who you're becoming. Stay true to that.",
        "Your clarity in that moment was correct. Trust past you.",
        "Future you is who you're working for. Don't stop.",
        "This block is proof you take your own goals seriously.",
        "The reason for this block is still real. The reason never expired.",
        "Your future is built in micro-decisions. This is one. Make it count.",
        "Future you has more time because they stopped losing it here.",
        "This app didn't build your goals. You built your goals. Build them.",
        "The wall is a gift from your past self. Receive it with gratitude.",
        "Your vision is more real than this urge. Stand with the vision.",
        "Future you is shaped by the times you chose purpose over impulse.",
        "This block is you honoring the commitment you made to your own life.",
        "Your future self has what they wanted because they chose it here.",
        "The block is not an obstacle. It's the path.",
        "Your attention is the thing. Guard the thing.",
        "Future you is grateful. Present you will be too.",
        "This wall is made of good judgment. Good judgment ages well.",
        "Your goals are still live. This block is keeping them that way.",
        "Future you has real wins because they stopped chasing fake ones.",
        "The block is the most honest thing you ever did for yourself.",
        "Your purpose is bigger than this urge. It was always bigger.",
        "Future you has depth. It started with the decision to go deeper.",
        "This block is trust, discipline, and direction made solid.",
        "Your future self says: you were right to walk away. Walk away.",
        "The wall stands for you. Stand with it.",
        "Future you exists because present you made choices like this one."
    )

    private val blockedPrompts = arrayOf(
        "The algorithm said no. Comeback tomorrow.",
        "App said no lil bro. Comeback tomorrow.",
        "Touch grass blud. Comeback tomorrow.",
        "Not a chance nga. Comeback tomorrow.",
        "Door's locked bestie. Comeback tomorrow.",
        "Your future self said absolutely not. Comeback tomorrow.",
        "The internet will survive without you. Comeback tomorrow.",
        "Nuh uh. Comeback tomorrow.",
        "Wrong time babe. Comeback tomorrow.",
        "Server is down. (It's not, but act like it.) Comeback tomorrow.",
        "You got blocked by yourself. Legendary. Comeback tomorrow.",
        "Access denied king. Comeback tomorrow.",
        "This app said not today. Comeback tomorrow.",
        "You already knew. Comeback tomorrow.",
        "The vibes said no. Comeback tomorrow.",
        "Not it chief. Comeback tomorrow.",
        "Lmao no. Comeback tomorrow.",
        "The wall said hello. Comeback tomorrow.",
        "Bruh you literally blocked yourself. Comeback tomorrow.",
        "No entry fam. Comeback tomorrow.",
        "Your dopamine said chill. Comeback tomorrow.",
        "Plot twist: you're the one who closed the door. Comeback tomorrow.",
        "Swipe left on this app. Comeback tomorrow.",
        "Error 403: You told me no. Comeback tomorrow.",
        "Bestie this is not the vibe rn. Comeback tomorrow.",
        "Hard pass from your past self. Comeback tomorrow.",
        "The lock is the lore. Comeback tomorrow.",
        "Not today Satan. Comeback tomorrow.",
        "Gone fishing (your focus is). Comeback tomorrow.",
        "Big no from the council. Comeback tomorrow.",
        "You literally set this up so go touch grass. Comeback tomorrow.",
        "Main character doesn't scroll here. Comeback tomorrow.",
        "Wrong timeline babe. Comeback tomorrow.",
        "Sir/ma'am this is a blocked app. Comeback tomorrow.",
        "Respectfully, nope. Comeback tomorrow.",
        "The universe said redirect. Comeback tomorrow.",
        "This ain't it fam. Comeback tomorrow.",
        "App is on a gap year. Comeback tomorrow.",
        "The plug is out. Comeback tomorrow.",
        "Zero access, full send elsewhere. Comeback tomorrow.",
        "You've been redirected by your own brain. Comeback tomorrow.",
        "Case closed bestie. Comeback tomorrow.",
        "Nope nope nope. Comeback tomorrow.",
        "Try again never. (Joke — try tomorrow.) Comeback tomorrow.",
        "404 scrolling not found. Comeback tomorrow.",
        "This app is in the DND zone. Comeback tomorrow.",
        "You're being protected from yourself rn. Comeback tomorrow.",
        "The bit is up. Comeback tomorrow.",
        "Not your hour king. Comeback tomorrow.",
        "Slay but make it productive. Comeback tomorrow.",
        "App went ghost. Comeback tomorrow.",
        "You literally wrote the code that says no. Comeback tomorrow.",
        "Full denial mode activated. Comeback tomorrow.",
        "Blocked by the main character (you). Comeback tomorrow.",
        "Your neurons said log off. Comeback tomorrow.",
        "This is a restricted zone superstar. Comeback tomorrow.",
        "No shot. Comeback tomorrow.",
        "Standing order: not today. Comeback tomorrow.",
        "The door is locked from inside and you're outside. On purpose. Comeback tomorrow.",
        "Access revoked by your better judgment. Comeback tomorrow.",
        "Babe this app is on time-out. Comeback tomorrow.",
        "Imagine trying to scroll rn. Comeback tomorrow.",
        "Denied. With love. Comeback tomorrow.",
        "Your screen time said enough. Comeback tomorrow.",
        "This is the wall talking. Hello. Comeback tomorrow.",
        "NPC behavior detected. Access blocked. Comeback tomorrow.",
        "You set this lock in cold blood. Comeback tomorrow.",
        "The exit is everywhere except here. Comeback tomorrow.",
        "Not the vibe, not the place. Comeback tomorrow.",
        "Zero scrolls given today. Comeback tomorrow.",
        "Big locked energy. Comeback tomorrow.",
        "The boss, the screen, and you all said no. Unanimous. Comeback tomorrow.",
        "Redirected to real life. Comeback tomorrow.",
        "You know why this is here. Comeback tomorrow.",
        "This lane is closed bestie. Comeback tomorrow.",
        "Scrolling is not on the schedule. Comeback tomorrow.",
        "The prophecy said not today. Comeback tomorrow.",
        "Error: too much main character energy to waste on this. Comeback tomorrow.",
        "Bro the app is literally asleep rn. Comeback tomorrow.",
        "Still no. Will continue to be no. Comeback tomorrow.",
        "The council has spoken: nuh uh. Comeback tomorrow.",
        "Step away from the feed. Comeback tomorrow.",
        "This is a no-scroll zone, have a day. Comeback tomorrow.",
        "App has left the chat. Comeback tomorrow.",
        "Wrong app, wrong time, right choice. Comeback tomorrow.",
        "Chronically offline era begins now. Comeback tomorrow.",
        "Negative ghost rider. Comeback tomorrow.",
        "Even the app is tired. Comeback tomorrow.",
        "You are the wall. Comeback tomorrow.",
        "Redirecting to literally anything better. Comeback tomorrow.",
        "This spot is taken by your goals. Comeback tomorrow.",
        "No pasarán. Comeback tomorrow.",
        "Lil bro tried to scroll and respawns tomorrow. Comeback tomorrow.",
        "App said log off. App was right. Comeback tomorrow.",
        "The vibe said redirect. Comeback tomorrow.",
        "Not unlocking this one, champ. Comeback tomorrow.",
        "This app is fully offline for your benefit. Comeback tomorrow.",
        "Held the line. Comeback tomorrow.",
        "Sent to voicemail. Comeback tomorrow.",
        "This is not the way. Comeback tomorrow.",
        "The gate is closed and the gatekeeper is you. Comeback tomorrow.",
        "App went on a walk. Comeback tomorrow.",
        "Bounced at the door. Comeback tomorrow.",
        "Your future self set this trap. Fall for it. Comeback tomorrow.",
        "No entry, no drama. Comeback tomorrow.",
        "The scroll ends here bestie. Comeback tomorrow.",
        "Wrong move but good catch. Comeback tomorrow.",
        "This app ghosted you on purpose. Comeback tomorrow.",
        "Your focus said bye. Comeback tomorrow.",
        "You literally wrote your own ban. Comeback tomorrow.",
        "Blocked by the legend that is you. Comeback tomorrow.",
        "The no is final bestie. Comeback tomorrow.",
        "Closed until further genius. Comeback tomorrow.",
        "This lane is reserved for your goals only. Comeback tomorrow.",
        "Out of office. Comeback tomorrow.",
        "Main character doesn't fall for this. Comeback tomorrow.",
        "The app is doing time. Comeback tomorrow.",
        "W choice setting this up. Now walk away. Comeback tomorrow.",
        "Not it, fam. Not it. Comeback tomorrow.",
        "You got blocked by the smartest person you know (yourself). Comeback tomorrow.",
        "Nope button was pressed. Comeback tomorrow.",
        "The algorithm was defeated by your past self. Comeback tomorrow.",
        "App requested a rain check. Comeback tomorrow.",
        "Door's closed, window's open — go look out the window. Comeback tomorrow.",
        "No scroll for you. Comeback tomorrow.",
        "Denied at the threshold. Comeback tomorrow.",
        "Your goals blocked your scroll. Comeback tomorrow.",
        "Touch some grass real quick. Comeback tomorrow.",
        "App is in time-out (deserved). Comeback tomorrow.",
        "Scrolling privileges revoked. Comeback tomorrow.",
        "This version of you doesn't open this app today. Comeback tomorrow.",
        "The plot doesn't go here. Comeback tomorrow.",
        "Zero access fam. Zero. Comeback tomorrow.",
        "Not a glitch. A feature. Comeback tomorrow.",
        "You did this. And it was correct. Comeback tomorrow.",
        "Even this app knows you're better than this. Comeback tomorrow.",
        "Blocked. Respectfully. Comeback tomorrow.",
        "Full send — elsewhere. Comeback tomorrow.",
        "App locked itself for your own good. Comeback tomorrow.",
        "Hard block, soft landing. Go outside. Comeback tomorrow.",
        "Nuh uh buddy. Comeback tomorrow.",
        "Request denied, have a great day. Comeback tomorrow.",
        "This app is on a sabbatical. Comeback tomorrow.",
        "Your self-discipline was right. Comeback tomorrow.",
        "Imagine scrolling rn. Wild. Comeback tomorrow.",
        "Step one of your glow up: this wall. Comeback tomorrow.",
        "The wall is built, the wall holds. Comeback tomorrow.",
        "No vibes here, all vibes elsewhere. Comeback tomorrow.",
        "App said read a book. Comeback tomorrow.",
        "Can't let you do that, star fox. Comeback tomorrow.",
        "Locked by the goat (you). Comeback tomorrow.",
        "You cannot pass. (Tolkien voice.) Comeback tomorrow.",
        "Zero percent chance of entry. Comeback tomorrow.",
        "Turn back, soldier. Comeback tomorrow.",
        "This is your villain origin block. Comeback tomorrow.",
        "The whole feed is gone. (For now.) Comeback tomorrow.",
        "Bestie the app is asleep. Comeback tomorrow.",
        "Not your circus, not your scroll. Comeback tomorrow.",
        "The lock goes brrrr. Comeback tomorrow.",
        "Go drink some water. App's closed. Comeback tomorrow.",
        "Blocked by the smartest version of you. Comeback tomorrow.",
        "No app today, only main character moments. Comeback tomorrow.",
        "The vibe departed. Comeback tomorrow.",
        "You were right to set this. Still right now. Comeback tomorrow.",
        "No, no, and no. Comeback tomorrow.",
        "404: scrolling has left the building. Comeback tomorrow.",
        "App is giving not available. Comeback tomorrow.",
        "Blocked by sheer excellence. Comeback tomorrow.",
        "Log off, level up. Comeback tomorrow.",
        "This isn't it and you know it. Comeback tomorrow.",
        "The gatekeeper said nope. Comeback tomorrow.",
        "Access expired. So did the need. Comeback tomorrow.",
        "Closed for personal growth. Comeback tomorrow.",
        "App is on a mission. Not your mission. Comeback tomorrow.",
        "The no was always here. Comeback tomorrow.",
        "No lil bro, not this time. Comeback tomorrow.",
        "Step outside, skill issue addressed. Comeback tomorrow.",
        "Blocked on all levels, no exceptions. Comeback tomorrow.",
        "The algorithm has left the chat. Comeback tomorrow.",
        "Zero scroll energy today. Comeback tomorrow.",
        "This app is under construction (indefinitely). Comeback tomorrow.",
        "Wrong turn, right wall. Comeback tomorrow.",
        "Signal lost. Go find yours. Comeback tomorrow.",
        "The screen said later. Much later. Comeback tomorrow.",
        "You're locked out of the trap house, king. Comeback tomorrow.",
        "Off the menu today. Comeback tomorrow.",
        "App is busy not existing for you. Comeback tomorrow.",
        "The bouncer said nah. Comeback tomorrow.",
        "Respawn point is tomorrow. Comeback tomorrow.",
        "You have been gently but firmly redirected. Comeback tomorrow.",
        "Blocked for the greater good. Comeback tomorrow.",
        "App is doing a digital detox. Coincidentally so are you. Comeback tomorrow.",
        "No vibes, no entry. Comeback tomorrow.",
        "The block was the glow up. Comeback tomorrow.",
        "Server maintenance: your focus. Comeback tomorrow.",
        "App goes bye bye for now. Comeback tomorrow.",
        "Not today my friend. Not today. Comeback tomorrow.",
        "The lock said I got you. It does. Comeback tomorrow.",
        "That's a no from me dawg. Comeback tomorrow.",
        "The app is giving you nothing today. Comeback tomorrow.",
        "Access terminated, sanity preserved. Comeback tomorrow.",
        "This is a judgment-free no. Comeback tomorrow.",
        "You're too evolved for this right now. Comeback tomorrow.",
        "Go text someone real. App closed. Comeback tomorrow.",
        "The wall says hi. Hi. Comeback tomorrow.",
        "Certified blocked. Comeback tomorrow.",
        "No way through, nice try. Comeback tomorrow.",
        "Blocked by ambition. Comeback tomorrow.",
        "This app doesn't open for you today. You set it up that way. Comeback tomorrow.",
        "Entry refused, character unlocked. Comeback tomorrow.",
        "The feed is fed up. Comeback tomorrow.",
        "App is on airplane mode forever (until tomorrow). Comeback tomorrow.",
        "Lil bro you built this cage. You're free actually. Comeback tomorrow.",
        "Go take a walk or something. App's locked. Comeback tomorrow.",
        "Hard no, soft landing. Comeback tomorrow.",
        "The vault is sealed. Comeback tomorrow.",
        "App called in sick. Comeback tomorrow.",
        "This is a restricted zone. Have a snack, go outside. Comeback tomorrow.",
        "Your future self left a sign here: don't. Comeback tomorrow.",
        "Blocked in all dimensions. Comeback tomorrow.",
        "App is unavailable for comment. Comeback tomorrow.",
        "You locked yourself out. That was the plan. Comeback tomorrow.",
        "The clock said nope. Comeback tomorrow.",
        "Gone to find better things. Go find them. Comeback tomorrow.",
        "Bestie you literally said no to yourself. Respect. Comeback tomorrow.",
        "Scroll blocked. Vibe unblocked. Comeback tomorrow.",
        "The energy is not here. Comeback tomorrow.",
        "Locked, sealed, delivered to your future self. Comeback tomorrow.",
        "App is mid. You're not. Comeback tomorrow.",
        "No access, high ground maintained. Comeback tomorrow.",
        "This was a trap. You laid it. You win. Comeback tomorrow.",
        "Go read something fr. App's closed. Comeback tomorrow.",
        "Offline is the new online. Comeback tomorrow.",
        "Access denied by your own executive function. Comeback tomorrow.",
        "App tried. You said no. W. Comeback tomorrow.",
        "Not your time, not your scroll. Comeback tomorrow.",
        "App quarantined from your attention. Comeback tomorrow.",
        "Lil bro the block is real. Comeback tomorrow.",
        "Log off. Glow up. Same thing. Comeback tomorrow.",
        "The app is closed for auditing. Comeback tomorrow.",
        "No entry, full class. Comeback tomorrow.",
        "Not the one, not today. Comeback tomorrow.",
        "Blocked by brains. Comeback tomorrow.",
        "Step away from the phone, king. Comeback tomorrow.",
        "Certified not available. Comeback tomorrow.",
        "This door goes nowhere you want to be. Comeback tomorrow.",
        "The craving said scroll. You said no. You win. Comeback tomorrow.",
        "Blud you're the one who blocked this. Comeback tomorrow.",
        "Full stop. Go outside. Comeback tomorrow.",
        "App is chillin without you. Comeback tomorrow.",
        "The pause was the point. Comeback tomorrow.",
        "Nope has entered the chat. Comeback tomorrow.",
        "App is in witness protection. Comeback tomorrow.",
        "This lane is closed, king. Pick another. Comeback tomorrow.",
        "You built the wall. You win. Comeback tomorrow.",
        "The app missed you. The block caught you. Comeback tomorrow.",
        "Blocked with precision. Comeback tomorrow.",
        "Still no. New day, same no. Comeback tomorrow.",
        "The no is structural. Comeback tomorrow.",
        "App ghosted you on purpose, with love. Comeback tomorrow.",
        "Not available at this time or ever (today). Comeback tomorrow.",
        "Redirected by the system you built. Comeback tomorrow.",
        "The wall doesn't negotiate. Comeback tomorrow.",
        "Lil bro go eat something and come back never (today). Comeback tomorrow.",
        "Access expired at your request. Comeback tomorrow.",
        "Blocked by the block that blocks. Comeback tomorrow.",
        "Zero percent entry chance. Comeback tomorrow.",
        "Closed. Locked. Done. Comeback tomorrow.",
        "The app is unavailable in your territory today. Comeback tomorrow.",
        "Blud you set this up yourself. Comeback tomorrow.",
        "Out of service. Into focus. Comeback tomorrow.",
        "Standing firm since you set this up. Comeback tomorrow.",
        "The wall is immovable today. Comeback tomorrow.",
        "App is giving nothing and that's exactly right. Comeback tomorrow.",
        "This is the app that isn't open. Comeback tomorrow.",
        "Scroll? In this economy? Blocked. Comeback tomorrow.",
        "App has no energy for this. Neither should you. Comeback tomorrow.",
        "Blocked by executive order (yours). Comeback tomorrow.",
        "Full offline mode, main character mode. Comeback tomorrow.",
        "No entry vibes only. Comeback tomorrow.",
        "App couldn't make it today. Comeback tomorrow.",
        "Zero, zip, nada. Comeback tomorrow.",
        "Bruh the block is still there. Comeback tomorrow.",
        "The lock outwitted the craving. Comeback tomorrow.",
        "Lil bro go outside, the app is gone. Comeback tomorrow.",
        "Blud it's locked fam. Comeback tomorrow.",
        "Closed by law (your law). Comeback tomorrow.",
        "App evicted from your time. Comeback tomorrow.",
        "The block is the boss. Comeback tomorrow.",
        "Not happening, not today, not now. Comeback tomorrow.",
        "This wall was built on a good day. Today is also a good day. Comeback tomorrow.",
        "App said see ya. Comeback tomorrow.",
        "You're the gatekeeper. Gate is kept. Comeback tomorrow.",
        "System working as intended. Comeback tomorrow."
    )

    fun getRandomPrompt(): String = reflectionPrompts.random()

    fun getUnblockPrompt(): String = unblockPrompts.random()

    fun getBlockedPrompt(): String = blockedPrompts.random()
}
