package app.subconsciously.helper

import app.subconsciously.data.RadarSnapshot

object RadarInsightEngine {

    private const val TH_HIGH  = 0.65f
    private const val TH_LOW   = 0.35f
    private const val TH_DELTA = 0.08f

    private val drop = listOf(
        "shake it off, next one",
        "that happened, now what",
        "not the first time, won't be the last",
        "you bounce back fast here",
        "everybody slips, that's real",
        "it's just a moment, move",
        "we fix things quick around here",
        "one play doesn't end the game",
        "reset is part of the process",
        "that's data, not defeat",
        "nothing to carry forward from this",
        "you already know what to do next",
        "one rough patch, that's it",
        "this doesn't define where you're going",
        "just a blip, nothing permanent",
        "real ones get back up fast",
        "nothing broken, just a detour",
        "you been here before and walked out",
        "it's fine, you're already past it",
        "ain't nothing that can't be reset",
        "this is just what happened today",
        "no damage, just a moment",
        "tomorrow starts fresh, for real",
        "you don't owe anyone a perfect day",
        "clean slate is always available",
        "that's not who you are, just what happened",
        "one bad move don't erase progress",
        "quick reset, back to it",
        "you already handled worse than this",
        "nothing permanent happened here",
        "this one doesn't count against you",
        "the next moment is already different",
        "big moves still ahead, this ain't it",
        "you're already thinking about the next step",
        "every setback here gets addressed quick",
        "not a failure, just a signal",
        "that information is useful, not fatal",
        "you've reset before and been fine",
        "nothing about this requires guilt",
        "dust settles fast when you let it",
        "real talk, this moment is already over",
        "one thing at a time, starting now",
        "you can fix anything fast when you're ready",
        "the comeback is already in motion",
        "no one's keeping score on this one",
        "whatever just happened, you're still standing",
        "nothing here is too big to move past",
        "you get up fast, that's just how it goes",
        "this ain't the moment that stops you",
        "you've seen bigger setbacks clear out",
        "that's done, this is now",
        "it happens to everyone, no exception",
        "you didn't come this far to stop here",
        "one moment off doesn't derail anything",
        "you fix it and keep moving, simple",
        "that was just noise, not direction",
        "the path didn't change, just the step",
        "you're already past this in your head",
        "nothing here needs more than a reset",
        "real ones don't dwell, they adjust",
        "that slip tells you something useful",
        "you already know the next move",
        "this is just part of the longer story",
        "happens fast, recovers fast, that's you",
        "no drama needed here, just a pivot",
        "you can start again right this second",
        "ain't nothing here you can't come back from",
        "that's just one chapter, not the book",
        "every reset moves you forward eventually",
        "you don't linger, you adjust",
        "what just happened doesn't own tomorrow",
        "this is the kind of thing that fades quick",
        "no need to overthink what already passed",
        "you already know how to shake this off",
        "quick fix, back on track",
        "that's a one-time thing, not a pattern yet",
        "you've bounced back from bigger, lowkey",
        "nothing permanent happened here",
        "the reset button is always right there",
        "one off-moment, that's the whole story",
        "you keep it moving, that's real",
        "this is not the version of you that stays down",
        "it was just a moment, already gone",
        "no weight to carry from this one",
        "you fix things and don't look back",
        "that's out of your system now",
        "you already know this passes quick",
        "this is small compared to what's ahead",
        "you repair things fast, always have",
        "one step back don't erase three forward",
        "that's just the process doing its thing",
        "nobody perfect every day, that's real",
        "you don't need a perfect record to move",
        "this one gets left right here",
        "you are not what just happened",
        "that slip is already in the past tense",
        "the next right thing is still available",
        "you get to decide what this means",
        "nothing about this changes the direction",
        "real talk — this is just weather, not climate",
        "you don't carry yesterday's losses here",
        "that was a blip on a long clear road",
        "one day like this won't set the pattern",
        "you already have what it takes to reset",
        "nothing got permanently changed by this",
        "a clean start is always one moment away",
        "you know how to get back to yourself",
        "this is the kind of thing you leave behind",
        "no guilt needed, just the next step",
        "you been through worse and came out clear",
        "that's just the dip before the climb",
        "you've handled this before without drama",
        "it's done, nothing to revisit",
        "you take care of it and keep rolling",
        "this is the part where you just reset",
        "everything is fixable from right here",
        "no score here, just direction",
        "you already know this doesn't stick",
        "the bounce is already starting",
        "that moment is over, this one is new",
        "no aftermath needed on this one",
        "you've walked out of bigger rooms than this",
        "this is temporary by nature",
        "you don't let this kind of thing linger",
        "one adjustment and you're already back",
        "that's the full extent of it, nothing more",
        "you repair fast and don't make it a thing",
        "this doesn't have to mean anything more",
        "lowkey this is just a moment, that's all",
        "you got through it, now you're through it",
        "the next version of this moment is better",
        "you don't build guilt here, you build momentum",
        "this passes quicker than it feels",
        "ain't the first reset and it won't break you",
        "you already let it go a little",
        "just a detour, same destination",
        "the path is still clear after this",
        "you know how to come back from a moment",
        "this is the reset you needed anyway",
        "no drama, just the next move",
        "you don't owe this moment more than it gets",
        "it's just data showing you something",
        "you already know what comes next",
        "this is the kind of thing that clears fast",
        "everybody has days like this, for real",
        "nothing here that can't be adjusted quick",
        "you fix it without making it a whole thing",
        "that's just today, not forever",
        "the rebound is already in motion",
        "you are already bigger than this moment",
        "one reset, that's the move right now",
        "this is lighter than it feels, trust",
        "nothing about this is catastrophic",
        "you know the difference between a slip and a fall",
        "quick acknowledgment, then you move",
        "this one doesn't follow you out the door",
        "you don't make more of this than it is",
        "just note it and keep going",
        "that was the thing, now it's done",
        "nothing requiring a whole breakdown here",
        "you handle things and move on, always",
        "this moment doesn't get more than a second",
        "you already made it through the harder parts",
        "that's just a reset point, use it",
        "you fix things fast and clean",
        "no need to sit in this one long",
        "you move through things, not around them",
        "this is exactly the kind of thing that fades",
        "you're already adjusting without realizing",
        "it's a moment, not a movement",
        "you take what happened and redirect",
        "this is the quick pivot you already know",
        "no damage done, just a moment lived",
        "you don't give this more power than it deserves",
        "that's out of the way now",
        "the reset is already working",
        "you know how to get back quick",
        "one thing off doesn't knock you off",
        "this is workable, everything is workable",
        "you already started coming back from it",
        "that's not a hole, just a dip",
        "you pick yourself up fast, that's built in",
        "nothing stuck, just passed through",
        "you leave it here and step forward",
        "that moment had nothing on you",
        "the ground is still solid under you",
        "you don't need to explain or justify this",
        "it happened, you're good, keep going",
        "this is the reset and it's already done",
        "you know the difference between a stumble and a stop",
        "nothing about this requires a verdict",
        "you let it go easier than you think",
        "that's just one frame in a long film",
        "you're still in it, that's what matters",
        "this is small by the standards you're building",
        "you get back on track fast, always",
        "that moment is already yesterday",
        "you're already looking forward, see"
    )

    private val struggling = listOf(
        "you noticed, that's not nothing",
        "awareness showed up, even if control didn't",
        "you caught it, that's the first win",
        "you saw it and that changes things",
        "real talk — noticing is the hardest part",
        "the fact you're aware is already different",
        "you clocked it before it fully took over",
        "that moment of pause was real",
        "not fully automatic anymore, for real",
        "something in you is watching now",
        "you noticed it happening, that counts",
        "the awareness is building, even if slow",
        "you saw it coming this time",
        "that recognition is worth something",
        "even if you kept going, you noticed",
        "you're not running on autopilot completely",
        "the part of you that sees it is growing",
        "you're fighting it even when it wins",
        "that resistance was real, even if small",
        "noticing is half the work, straight up",
        "you're working against something strong",
        "even through it, there was a moment of clarity",
        "the struggle means you're still in it",
        "you haven't stopped caring, that's clear",
        "that tug you felt before going — that was you",
        "you're not surrendering, you're building",
        "the awareness is sharper than before",
        "you see what's happening, that's not small",
        "that friction you felt was real progress",
        "you caught yourself mid-motion",
        "something is different even if it doesn't look it",
        "the fight is happening, even quietly",
        "you noticed the urge before acting",
        "that second of pause meant something",
        "you're more aware than the behavior shows",
        "the part that sees is getting louder",
        "you're in it and fighting it simultaneously",
        "that observation before the action matters",
        "you haven't gone fully automatic",
        "real talk — you're still showing up in there",
        "that internal voice got a word in",
        "you saw it, that's the work right there",
        "the awareness is real even when control dips",
        "you caught yourself, even if just for a second",
        "that's not nothing — you noticed",
        "the observer in you is active",
        "you know what's happening, that's different",
        "that moment of recognition was real",
        "the struggle is evidence you still care",
        "you're not checked out, you're checked in",
        "even mid-slip you saw it clear",
        "that's the kind of awareness that grows",
        "you know the pattern now, that's progress",
        "the noticing is getting faster",
        "you caught it before it fully settled",
        "that discomfort you felt was a signal working",
        "you're fighting with more awareness than before",
        "the battle is happening inside, for real",
        "you're not unaware, you're just building control",
        "that pause before acting — that was you",
        "you see it clearer than you act on it, for now",
        "the gap between seeing and stopping is closing",
        "you're more conscious than you were",
        "that moment of recognition is worth something big",
        "the awareness is working, just not all the way yet",
        "you noticed and that's not where you started",
        "this is what the building phase looks like",
        "you're still in there, fighting it quiet",
        "that internal check-in happened, that matters",
        "you're developing the thing that stops it",
        "even if control wasn't there, awareness was",
        "real talk — that notice was a win",
        "something in you is recalibrating",
        "you felt the pull and you named it",
        "that's awareness doing its job",
        "you're not sleepwalking through it anymore",
        "you caught the moment, even mid-stream",
        "that recognition is getting harder to ignore",
        "you're aware enough to feel the conflict",
        "the fact that it bothers you means something",
        "you noticed the drift before it went too far",
        "that internal signal fired, and you heard it",
        "you're growing the muscle that eventually stops it",
        "the awareness came first this time",
        "you saw yourself in it, that's clarity",
        "even the struggle is more conscious now",
        "you're not numb to it, that's the difference",
        "that check-in mid-moment was real work",
        "you're tracking it even when you're in it",
        "the part of you that knows is louder today",
        "you noticed it before the moment was over",
        "that's a different kind of awareness showing up",
        "you didn't lose yourself completely in it",
        "the signal got through, even if action lagged",
        "you're watching yourself more carefully now",
        "that friction between knowing and doing is normal",
        "you caught the wave while you were still on it",
        "real — the noticing is the foundation",
        "you're aware in a way you weren't before",
        "that awareness has real weight to it",
        "you're building control through awareness first",
        "the observer is active and getting stronger",
        "you noticed and couldn't look away",
        "even if you went, you knew, and that's growth",
        "that recognition happened faster than before",
        "you're on to yourself in a way that compounds",
        "the awareness isn't decorative — it's building",
        "you clocked it and that's more than most",
        "you're in the hard part of the change",
        "that moment of clarity wasn't wasted",
        "you noticed the pattern mid-pattern",
        "the noticing is the thing that eventually wins",
        "you're not on autopilot anymore, even if close",
        "that inner signal is getting easier to hear",
        "you're learning your own patterns in real time",
        "the gap is closing between seeing and stopping",
        "you saw it and had a reaction to it",
        "that reaction is the data you needed",
        "you're paying attention in a new way",
        "even going through it, you saw yourself do it",
        "that's the kind of awareness that accumulates",
        "you're not numb to the pattern anymore",
        "you caught the moment in real time",
        "the noticing is the first real move",
        "you had a feeling before and honored it",
        "even the slip came with a signal this time",
        "you're more present in the struggle now",
        "that awareness is the seed of control",
        "you felt it and you named it in your head",
        "the struggle is sharper because you're aware",
        "you're not just going through the motions",
        "that pull you recognized — you're working it",
        "you saw the choice even if you didn't take it",
        "the space between urge and action is opening",
        "you noticed, that's step one of something bigger",
        "real talk — you're building something real here",
        "the resistance you felt was your growth working",
        "you caught it mid-fall and held some ground",
        "you're aware and that changes everything eventually",
        "that noticing moment was louder than before",
        "you saw it, felt it, and still showed up",
        "the signal is stronger than it used to be",
        "you're developing the thing that matters most",
        "you noticed the whole arc while in it",
        "that's awareness on a different level now",
        "you're not unconscious to it anymore, straight up",
        "even in the doing you saw the doing",
        "the watching part of you is wide awake",
        "you caught yourself at a deeper point this time",
        "that awareness is worth more than it looks",
        "you're in it but you see it too",
        "that dual view is exactly what changes things",
        "you noticed the loop while you were in the loop",
        "real — the seeing is changing the doing",
        "you're awake to it in a new way",
        "the awareness came quick this time",
        "you saw yourself clearly even mid-moment",
        "that's the sharpest your awareness has been",
        "you noticed before the moment fully passed",
        "the signal got through loud this time",
        "you felt the conflict and sat with it a second",
        "even if control didn't show, awareness did",
        "that recognition is laying real groundwork",
        "you see the thing now, and that's the whole game",
        "you're working through the hardest layer",
        "that moment of friction was productive",
        "you didn't black out into it — you watched",
        "the awareness you have now is new territory",
        "you caught the trigger before it fully fired",
        "that inner flag went up and you heard it",
        "you're not where you were, awareness-wise",
        "even struggling, you're seeing it straight",
        "you feel the pull differently now",
        "the noticing is earlier in the cycle",
        "you saw the start of it this time",
        "that moment of self-observation was real",
        "you're aware of the mechanism now",
        "the signal fires earlier when you're paying attention",
        "you're watching the pattern from inside it",
        "that kind of awareness is different in real life",
        "you saw yourself in the middle of it, for real",
        "the noticing is the foundation everything builds on",
        "you caught it before it became invisible",
        "that awareness came from somewhere real in you",
        "you're in the phase where noticing leads to more",
        "even through it, you were watching yourself",
        "the observer is you and it's getting strong",
        "you noticed the moment the urge showed up",
        "that recognition is accelerating now",
        "you're developing real-time self-awareness",
        "even if you went, you saw yourself go",
        "that's not passive awareness, it's active",
        "you caught it and held the observation",
        "the seeing is the most important part right now",
        "you noticed without judgment, that's growth",
        "that awareness is running ahead of the habit",
        "you're building something invisible but real",
        "even in the middle of it, you were there",
        "that noticing is compounding quietly",
        "you're more awake in this than you know"
    )

    private val expanding = listOf(
        "this is how it starts, quietly",
        "you're already shifting, even if it's small",
        "something better is forming here",
        "this version of you feels different",
        "you're not the same as before this moment",
        "you chose, not just reacted",
        "this was yours to decide",
        "this moment belonged to you",
        "you didn't have to follow the urge",
        "you're taking control back, step by step",
        "this is a better direction already",
        "this small shift adds up",
        "something good is building from here",
        "you're moving toward something better",
        "that's the move right there",
        "you're building something real",
        "this is what progress actually looks like",
        "you're doing something most people don't",
        "that choice had weight and you made it",
        "you're writing a different story right now",
        "this is the kind of shift that compiles",
        "you're growing in a way that sticks",
        "that was bigger than it looked",
        "you're thinking different now, that's clear",
        "this is the version of you that builds things",
        "you made the harder choice and that matters",
        "that move just changed something forward",
        "you're operating at a different level now",
        "this is what intentional living feels like",
        "you chose long-term over short-term",
        "that's the kind of choice that compounds",
        "you're building something no one can take",
        "this is the foundation of something big",
        "you took ownership of that moment",
        "that decision was yours and you made it right",
        "you're stacking wins now even if they're quiet",
        "this is how people change for real",
        "you did something different today",
        "that shift is going to matter later",
        "you're ahead of where you were, for real",
        "this is how the best version of you shows up",
        "you chose the harder road and that's everything",
        "that's not small — that's the whole thing",
        "you're operating with more intention now",
        "this moment is already paying forward",
        "you made a move that builds not depletes",
        "that choice reflects something growing in you",
        "you're stacking up differently now",
        "this is how big change actually works",
        "you're thinking bigger about yourself now",
        "that choice had your name on it, in a good way",
        "you're not the same person who started this",
        "this is growth that doesn't show up in mirrors",
        "you made a move that matters long-term",
        "that's a brick in something strong",
        "you're building like you mean it",
        "this is the direction that leads somewhere real",
        "you acted like the person you want to be",
        "that was the right call and you made it",
        "you're growing in real time",
        "this is the long game and you're playing it",
        "you're proving something to yourself right now",
        "that choice is compounding already",
        "you're doing the thing that matters most",
        "this is how momentum actually gets started",
        "you chose the version that builds",
        "that's a real move, not a performance",
        "you're writing better chapters now",
        "this is where the shift happens for real",
        "you made the move that reflects who you're becoming",
        "that decision was clean and it was yours",
        "you're building the bigger version of yourself",
        "this is the kind of day that matters later",
        "you stepped up when it counted",
        "that's agency and you just used it",
        "you're not reacting, you're directing",
        "this is the bigger picture in motion",
        "you proved you can choose differently",
        "that's how real change shows up",
        "you chose your future over your impulse",
        "this is the turn, right here",
        "you're moving like you know where you're going",
        "that move just opened something up",
        "you're taking up more space in the right way",
        "this is the version of you that shows up",
        "you're building real traction now",
        "that small win is bigger than it looks",
        "you made the right call for the bigger thing",
        "this is how it feels to be in control",
        "you're leading yourself forward",
        "that choice is adding to something solid",
        "you're doing it different and it shows",
        "this is real traction on a real path",
        "you're investing in yourself right now",
        "that move means more than the moment",
        "you're becoming something on purpose",
        "this is the thing that doesn't stop",
        "you proved to yourself you can do this",
        "that's the kind of choice big futures are built on",
        "you're building a record of real decisions",
        "this is slow and it's still the fastest way",
        "you're making it real by showing up",
        "that choice was the right one, clean",
        "you're not the same as yesterday's version",
        "this is the kind of progress that can't be faked",
        "you're thinking bigger than the urge",
        "that's you making a real investment",
        "you're growing in the direction that counts",
        "this is what building from the inside looks like",
        "you took control and it looked natural",
        "that's a move a stronger version makes",
        "you're acting aligned with who you're becoming",
        "this moment just added something real to you",
        "you chose the bigger picture over the quick hit",
        "that's the choice that separates the two versions",
        "you're in expansion mode, for real",
        "this is the kind of day that builds foundations",
        "you're making intentional moves now",
        "that decision stacks with the others",
        "you're not just trying anymore, you're doing",
        "this is the version of you that takes over",
        "you're operating on a different frequency now",
        "that's what real ownership looks like",
        "you're doing something that adds up",
        "this is how it grows from here",
        "you made a choice your future already thanks you for",
        "that move is already downstream from here",
        "you're compiling wins quietly",
        "this is the version that keeps going",
        "you're building something permanent",
        "that choice reflected real growth",
        "you're further along than it feels",
        "you proved the better version is real",
        "that's a signal you're running a different program",
        "you chose the life you actually want",
        "this momentum is yours to keep",
        "you're stacking up the right way now",
        "that was all you, clean and clear",
        "you're in building mode and it shows",
        "this is the slow burn that wins",
        "you made the move that counts",
        "that's real agency on display",
        "you're running your own play now",
        "this is the version of you that builds real things",
        "you made a choice aligned with your growth",
        "that move had your real values in it",
        "you're gaining ground without rushing it",
        "this is what discipline looks like in practice",
        "you chose the real thing over the easy thing",
        "that's a clean win on the board",
        "you're moving with real intention now",
        "this decision is already working for you",
        "you took real ownership right there",
        "that choice was yours and it was right",
        "you're building at a pace that lasts",
        "this is where real change gets its footing",
        "you're getting stronger at the thing that matters",
        "that moment reflected a cleaner version of you",
        "you made a move toward who you're becoming",
        "this is the growth that doesn't announce itself",
        "you proved the thing you wanted to prove",
        "that decision showed up right when needed",
        "you're showing up differently and it counts",
        "this is the quiet version of big change",
        "you chose with clarity this time",
        "that move came from a stronger place in you",
        "you're building the life that matches the person",
        "you took the long view and that's everything",
        "that choice has range to it",
        "you're not just surviving the moment, you're using it",
        "this is what it looks like when you choose yourself",
        "you made the move that the best version makes",
        "that was real-time growth, for real",
        "you're building from a different foundation now",
        "this is slow and it's exactly right",
        "you're operating with more agency than before",
        "that's you proving what you're capable of",
        "you're moving toward bigger without rushing",
        "this is the choice that opens doors",
        "you made the call that builds the thing",
        "that's evidence of real change",
        "you're running a different internal program now",
        "this is what gaining ground actually feels like",
        "you chose the version that grows",
        "that choice just made the next one easier",
        "you're building something here that holds",
        "this is the move that starts a run",
        "you're not playing small anymore",
        "that decision reflects your real direction",
        "you're compiling real wins now",
        "this version of you is already different",
        "you took the moment and ran with it right",
        "that's the kind of move that echoes forward",
        "you're acting like the person you're becoming",
        "this is the foundation, and it's solid",
        "you made a real move and it was clean",
        "that choice adds weight to the right side",
        "you're building the bigger story one move at a time"
    )

    private val awareness = listOf(
        "you saw the urge before it took over",
        "there was space before the action",
        "that pause changed something small",
        "you noticed it before it became automatic",
        "something shifted in how you see it",
        "you clocked it before it even moved",
        "you read the signal before it fired",
        "that's a different level of attention",
        "you caught it in the pre-move",
        "real sharp eyes on your own patterns",
        "you're watching yourself at a new depth",
        "that recognition came before anything else",
        "you intercepted your own reflex",
        "straight up — you saw it coming",
        "you caught the thing before the thing",
        "that kind of awareness is rare",
        "you clocked the trigger before it ran",
        "that's not just noticing — that's seeing",
        "you read yourself accurate just now",
        "the space you created was real",
        "you saw through it in real time",
        "that pause was more powerful than it looked",
        "you caught the start of the loop",
        "real talk — you're reading yourself clearly",
        "you saw the urge for what it is",
        "that space between urge and action — you made that",
        "you tracked the feeling before the behavior",
        "that's next-level self-awareness",
        "you noticed the automatic thing before it automated",
        "the moment you saw it, it changed",
        "you're moving with clarity now",
        "that recognition happened at the source",
        "you caught it upstream",
        "the observation changed the game",
        "you saw the whole arc before it played out",
        "that's seeing yourself from the outside while in it",
        "you read the room inside yourself accurately",
        "that insight came before the action, not after",
        "you're tracking things at the root level",
        "real — that kind of clarity is different",
        "you saw the pull and named it",
        "that naming changed its power",
        "you clocked the move before you made it",
        "the awareness you just showed is operating",
        "you caught the signal in its earliest form",
        "that's the sharpest version of noticing",
        "you're reading your own patterns like text",
        "that moment of clarity was precise",
        "you saw the loop at the start, not the end",
        "that pause was the whole ballgame",
        "you created space where there usually isn't any",
        "that's what it looks like when awareness is ahead",
        "you read yourself correct this time",
        "the space you made is where change lives",
        "you tracked the urge back to its start",
        "that kind of seeing changes things structurally",
        "you moved awareness ahead of instinct",
        "the clarity you just had is building",
        "you saw it before it could act on you",
        "that's the kind of awareness that leads somewhere",
        "you clocked the mechanism, not just the result",
        "real — that insight was at the right level",
        "you caught the thing at the root",
        "that recognition is operating at depth",
        "you saw through the surface of the habit",
        "that pause created a completely different outcome",
        "you're seeing at the level that actually matters",
        "that observation was sharp and it was real",
        "you saw the reflex before it could take over",
        "the gap you made between urge and action is the work",
        "you're running with more clarity than before",
        "that kind of noticing is real edge",
        "you read the moment before it could write itself",
        "that's awareness working at full strength",
        "you caught the automatic response pre-auto",
        "real clarity — you saw the thing clearly",
        "you tracked it at the source level",
        "that insight is working at the right depth",
        "you moved faster than the habit this time",
        "the space you created was the real win",
        "you're operating with clear internal vision",
        "that recognition went deeper than usual",
        "you caught the before-moment of the moment",
        "real — the awareness is running ahead now",
        "you saw the whole thing before it happened",
        "that kind of self-reading is rare and real",
        "you caught the trigger in the chamber",
        "the pause you created was intentional and real",
        "you're tracking yourself at the source",
        "that recognition came before any decision was made",
        "you saw what was really happening",
        "the pause created room you didn't have before",
        "you caught the wave before it broke",
        "that's seeing at the level that changes things",
        "you read the internal signal correctly",
        "the awareness you just showed is operating at depth",
        "you caught the move in pre-motion",
        "that observation is the kind that accumulates power",
        "you saw yourself accurately and that's not easy",
        "the clarity you have right now is different",
        "you clocked the pattern from the front end",
        "that's you operating with real self-knowledge",
        "you saw the mechanism not just the output",
        "the recognition came fast and it came right",
        "you're reading your own signals like a pro",
        "that awareness hit before the habit could form",
        "you caught the moment at the right frame",
        "real talk — that clarity is operating",
        "you saw it without being told to look",
        "the space you held before acting was earned",
        "you tracked the thing backward to its root",
        "that's what high-level self-awareness does",
        "you caught the start before the middle",
        "the observation was sharp and it came first",
        "you're reading yourself at the right level now",
        "that recognition came from a deep place",
        "you saw the urge, noted it, and had a moment",
        "real — that kind of seeing is rare",
        "you caught yourself before the moment ran",
        "the clarity you just showed is different from before",
        "you observed the thing from inside the thing",
        "that insight was working at the core",
        "you saw the reflex before it ran its course",
        "that space you made is the most important move",
        "you're watching with real sharpness now",
        "that observation was ahead of the action",
        "you caught the pattern mid-setup",
        "real — the seeing came before the doing",
        "you tracked the moment at its origin",
        "that kind of clarity leads to real agency",
        "you read the internal move before it happened",
        "the awareness you're showing is working",
        "you caught the before-moment and paused in it",
        "that's you using real self-knowledge",
        "you saw it from the inside and outside at once",
        "the recognition you had was on time",
        "you caught the urge in its early form",
        "real talk — that's a clear read on yourself",
        "you saw the pull before it pulled",
        "that awareness is operating at a new depth",
        "you tracked yourself to the source",
        "the insight that just happened was real",
        "you caught the signal before it became noise",
        "that kind of seeing is a real shift",
        "you read yourself with accuracy right now",
        "the pause you held carried real weight",
        "you saw it from the right angle",
        "that observation hit at the structural level",
        "you caught the trigger before it triggered",
        "real — you're operating with more internal clarity",
        "you saw the impulse for what it was",
        "the space before the action was yours",
        "you tracked the moment all the way back",
        "that recognition was earlier than before",
        "you saw through the surface without trying",
        "the awareness you showed is working forward",
        "you caught the automatic and held a beat",
        "real talk — the clarity you have is building",
        "you read the moment from the inside out",
        "that's the kind of insight that changes patterns",
        "you caught yourself pre-move and it counts",
        "the recognition you had was at the right level",
        "you saw the reflex and made space around it",
        "that awareness is ahead of the habit now",
        "you caught it before it became comfortable",
        "real — you're seeing at a different frequency",
        "you tracked the feeling to where it started",
        "the clarity you showed is operating at depth",
        "you saw the moment before it became a choice",
        "that's awareness running at the right speed",
        "you caught the pull in real time",
        "the observation you made was accurate and early",
        "you saw through the familiar feeling",
        "real talk — that seeing is different now",
        "you caught it and held the space",
        "the awareness is working faster than before",
        "you saw the loop at the entry point",
        "that recognition is running ahead of behavior",
        "you read yourself correctly and quickly",
        "the space you created is where everything happens",
        "you caught the thing before it became the thing",
        "real — that kind of insight is rare and real",
        "you saw the move before you made it",
        "that clarity is operating from the inside",
        "you tracked the signal all the way to the source",
        "the recognition came early and it was right",
        "you saw through the habit's disguise",
        "real talk — the seeing is getting sharper",
        "you caught the moment at the earliest point",
        "the awareness you're running is high level",
        "you saw what was really moving under there",
        "that recognition is the real leverage point",
        "you caught the root, not just the branch",
        "real — the clarity you showed is building on itself",
        "you saw the thing before it spoke",
        "the space you made was real and intentional",
        "you tracked yourself all the way through",
        "that observation came from a clear, clean place",
        "you caught the mechanism in real time",
        "the awareness is ahead of the curve now"
    )

    private val stable = listOf(
        "you're here, that's enough",
        "no rush, you're doing fine",
        "this feels lighter already",
        "this moment is yours",
        "this is enough for now",
        "you gave yourself a moment",
        "you stayed with yourself for a second",
        "steady is its own kind of strong",
        "you're holding ground, that matters",
        "this is what consistency looks like",
        "you're still in it and that's not nothing",
        "real quiet progress is still progress",
        "you're moving at the right pace for you",
        "that steadiness is the whole thing",
        "you're not rushing and that's wise",
        "this is a solid position to be in",
        "you're grounded right now and that's good",
        "nothing flashy, just real",
        "you're holding your line",
        "this steady thing is underrated",
        "you're showing up without drama",
        "that consistency has value",
        "you're not falling back, you're holding",
        "this is the kind of day that builds character",
        "you're in a good place, even if it's quiet",
        "nothing forced here, just real",
        "you're doing the thing without needing it to be big",
        "that groundedness is the foundation",
        "you're operating from a stable center",
        "this moment has its own quiet value",
        "you're not chasing anything right now",
        "that's a healthy place to be",
        "you're present and that's not small",
        "this stability is hard-earned",
        "you're standing on solid ground",
        "nothing to prove right now, just be",
        "you're holding steady and that's a real win",
        "this is the calm before the next move",
        "you're exactly where you need to be",
        "that steadiness has real strength in it",
        "you're doing well without making it loud",
        "this is the kind of consistent that wins long",
        "you're here and you're good, that's it",
        "this quiet stability is building something",
        "you're running clean right now",
        "nothing off, nothing forced",
        "you're in balance and that's no accident",
        "this is what a good baseline looks like",
        "you're not distracted by the noise right now",
        "that's a healthy relationship with the moment",
        "you're treating yourself right, lowkey",
        "this is the version of the day that sustains",
        "you're not burning out or burning down",
        "that kind of steadiness has range",
        "you're here, you're grounded, you're good",
        "this is the long-game version of a win",
        "you're not overthinking it and that's right",
        "nothing about this needs to be fixed",
        "you're holding your own energy right now",
        "that's the baseline that everything good builds on",
        "you're doing fine and it shows",
        "this steady rhythm is where real growth lives",
        "you're not white-knuckling anything",
        "that ease is earned, not accidental",
        "you're moving with the moment, not against it",
        "this is what equilibrium feels like",
        "you're in alignment right now",
        "that stability is its own accomplishment",
        "you're not fighting what is",
        "this is the version of today that works",
        "you're clear-headed and that matters",
        "nothing is off the rails, everything is solid",
        "you're running at a sustainable level",
        "that's the version of you that lasts",
        "you're not leaking energy anywhere right now",
        "this is a genuinely solid place to be",
        "you're managing yourself well",
        "that stability carries further than it looks",
        "you're not forcing anything and it shows",
        "this is the kind of steady that adds up",
        "you're in the flow without needing to announce it",
        "that groundedness is your foundation",
        "you're doing the work without the drama",
        "this is what healthy looks like in practice",
        "you're exactly where real growth is possible",
        "that calm is a kind of power",
        "you're not faking it, just living it",
        "this moment is clean and clear",
        "you're in a place where good things can grow",
        "that steady energy is worth protecting",
        "you're holding your center and that's everything",
        "this isn't boring, it's solid",
        "you're doing the most important kind of nothing",
        "that stillness has real content",
        "you're not spinning out anywhere",
        "this is the base camp everything launches from",
        "you're at peace with the moment, quietly",
        "that kind of stability doesn't come easy",
        "you're not in chaos and that's a real choice",
        "this steady thing is doing more than it looks",
        "you're here and handling it",
        "that groundedness is the thing that holds",
        "you're not pushed around right now",
        "this is what showing up clean looks like",
        "you're good and you don't need it to be bigger",
        "that equilibrium took work to get to",
        "you're running stable and that's the goal",
        "this is exactly the pace you need right now",
        "you're not overdoing it or underdoing it",
        "that steady middle ground is the hardest to hold",
        "you're comfortable with where you are",
        "this is the kind of day that sustains a week",
        "you're operating from a clear center",
        "that consistency is quiet and real",
        "you're not reacting, you're just being",
        "this is the baseline that everything else needs",
        "you're in your lane and moving steady",
        "that groundedness is protective",
        "you're not seeking anything extra right now",
        "this is what good maintenance feels like",
        "you're holding it together in the right way",
        "that steadiness is underrated in a big way",
        "you're doing fine and that's genuinely good",
        "this is the right pace, trust it",
        "you're not burning bright or burning out",
        "that balance is hard-won and real",
        "you're exactly where you should be",
        "this moment doesn't need anything added",
        "you're moving at the speed of sustainable",
        "that stable energy is where real things get built",
        "you're holding your ground without effort",
        "this is the version of you that lasts",
        "you're not chasing or avoiding",
        "that steadiness has depth to it",
        "you're grounded in a way that can handle what's next",
        "this is the foundation being laid",
        "you're doing the work of being okay",
        "that's not nothing — that's everything",
        "you're in a real and honest place",
        "this is what maintenance mode done right looks like",
        "you're not performing stability, you're feeling it",
        "that quiet is not empty, it's full",
        "you're giving yourself the right conditions",
        "this is the kind of okay that builds",
        "you're not rushing the next thing",
        "that unhurried quality is a real skill",
        "you're letting things settle and that's right",
        "this is the ground level and it's solid",
        "you're doing the thing that keeps you whole",
        "that calm has real substance",
        "you're in the middle of something good",
        "this is where good decisions get made",
        "you're not scattered or pulled apart",
        "that centering is real and it's working",
        "you're clear enough to see straight",
        "this is the version of today you can build on",
        "you're not maxed out or checked out",
        "that even keel is the secret move",
        "you're operating with a clear head",
        "this kind of stability is the whole game",
        "you're not borrowing tomorrow's energy",
        "that steady thing is the real competitive edge",
        "you're doing this at the right pace",
        "this is the quiet kind of winning",
        "you're holding the line without drama",
        "that steadiness is speaking for itself",
        "you're managing your energy well",
        "this moment is clean, take that",
        "you're in alignment with where you need to be",
        "that groundedness is the most solid thing about you",
        "you're big in the quiet way that counts",
        "this steady is building something solid",
        "you're not running hot or running cold",
        "that balanced state is where clarity lives",
        "you're doing this the right way",
        "this is the middle ground and it's powerful",
        "you're operating from a full tank",
        "that steadiness is the thing holding everything",
        "you're here, and here is exactly right",
        "this is the pace that gets you somewhere real",
        "you're not pushing past what's good",
        "that ease in the moment is earned",
        "you're breathing and that's the whole game sometimes",
        "this is what thriving quietly looks like",
        "you're doing fine in a way that's built to last",
        "that groundedness shows up when it matters",
        "you're in the right state to make good moves",
        "this moment is balanced and that matters",
        "you're not overcomplicating what's already working",
        "that steady rhythm is the engine",
        "you're holding your energy where it belongs",
        "this is what it looks like to be solid",
        "you're not burning the candle from both ends",
        "that stability is the base of everything good",
        "you're moving at the speed of real",
        "this is the kind of day that pays dividends",
        "you're in exactly the right gear",
        "that evenness is quiet strength",
        "you're doing this right and it's showing",
        "you're solid, and solid is everything right now"
    )

    // Excludes Time axis: week.time is always DEFAULT (0.5) so including it biases delta7
    private fun avgBehavior(snap: RadarSnapshot) =
        (snap.awareness + snap.control + snap.intention + snap.energy) / 4f

    fun selectPrompt(today: RadarSnapshot, week: RadarSnapshot, recentKeys: List<String>): String {
        val A = today.awareness
        val C = today.control
        val I = today.intention
        val delta7 = avgBehavior(today) - avgBehavior(week)

        val pool = when {
            // DROP: stop rate very low — app intercepts but user rarely resists
            // A is excluded: the forced reflection means A is always high; C is the real signal
            C < TH_LOW                                          -> drop
            // STRUGGLING: noticing (A high by design) but not consistently stopping
            A >= TH_HIGH && C < TH_HIGH                        -> struggling
            // EXPANDING: strong control AND improving trend vs weekly baseline
            delta7 > TH_DELTA && C >= TH_HIGH && I >= TH_HIGH -> expanding
            // AWARENESS: strong stop quality, not necessarily trending up
            A >= 0.75f && I >= 0.6f                             -> awareness
            else                                                 -> stable
        }

        val candidates = pool.filter { it !in recentKeys }
        return if (candidates.isNotEmpty()) candidates.random() else pool.random()
    }
}
